### ISSUE TITLE
Should floaterView be a UIControl or a UIView?

### ISSUE THREAD

**Issue by aarondaub** [Originate/OriginateScrollViewFloater#1]
I might be missing something but I don't see any reason for it to be a control and not a view.

**Comment by allewun** [comment]
Yeah I suppose it doesn't have to be, but this was an easy way to get the highlighted state when pressing the `floaterView`.

If there were an existing protocol that defined `-setHighlighted:` (is there one?), I'd've used it as the type. I guess I could define one. What do you think?

**Comment by aarondaub** [comment]
OH, I didn't see you were using anything on UIControl. If you're using something that it defines and UIView doesn't then you are right and I am wrong and stupid and shouldn't ever bother you again :(
